  name: Deploy React App to Azure Static Web Apps

on:
  push:
    branches:
      - main  # or the branch you want to deploy from
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy_job:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v2
        with:
          action: "upload"
          app_location: "/"
          output_location: "build"
          api_location: ""  # Set to the path of your API, if any
